#!/bin/bash

APP="mingus"

BUILD_HOST="elixir1.builder.priv.linky.one"
BUILD_USER="root"
BUILD_AT="/opt/edeliver/$APP/builds"

DELIVER_TO="/opt/$APP"

STAGING_HOSTS="mingus1.priv.linky.one"
STAGING_USER="root"

#PRODUCTION_HOSTS=$STAGING__HOSTS
#PRODUCTION_USER=$STAGING__USER

# For *Phoenix* projects, symlink prod.secret.exs to our tmp source
# pre_erlang_get_and_update_deps() {
#   local _prod_secret_path="/opt/edeliver/linky/prod.secret.exs"
#   if [ "$TARGET_MIX_ENV" = "prod" ]; then
#     __sync_remote "ln -sfn '$_prod_secret_path' '$BUILD_AT/apps/linky_web/config/prod.secret.exs'"
#   fi
# }
