#!/bin/bash
set -e

export NAME=mingus
export MIX_ENV=prod
mix deps.get
mix release

export REL_DIR=$(cd _build/${MIX_ENV}/rel/${NAME} && pwd)
rm -f ${REL_DIR}/package.tgz
(cd ${REL_DIR} && tar zcf package.tgz ./*)
export $1="${REL_DIR}/package.tgz"
echo "Release created in: ${REL_DIR}/package.tgz"
